### ISSUE TITLE
Updating license?

### ISSUE THREAD

**Issue by ffd8** [fbsamples/Canvas-Streaming-Example#11]
Have you considered [updating the license](https://engineering.fb.com/open-source/explaining-react-s-license/) of this repo to MIT? As mentioned in #3, this code offers a fastinating way to stream from the canvas to *any* RTMP server. While usage with Facebook Live is thoroughly documented in the readme, it would benefit the larger community to allow alternative server usage.

**Comment by randallb** [comment]
I'll see what I can do.

**Comment by randallb** [comment]
I checked with our team, and it sounds like we're going to keep the license as-is for now.

Thanks!

**Comment by ffd8** [comment]
@randallb many thanks for the quick reply and inquiry. That's too bad considering the [architecture](https://github.com/fbsamples/Canvas-Streaming-Example/raw/master/doc/architecture.png) passes multiple open licensed projects until reaching Facebook Live. Would be great if the team considered removing [line 5](https://github.com/fbsamples/Canvas-Streaming-Example/blob/ff9464f42fcf28ce885e609f411a4df5faa5846d/LICENSE#L5). Cheers
