### ISSUE TITLE
Canvas Streaming to HLS?

### ISSUE THREAD

**Issue by rayj00** [fbsamples/Canvas-Streaming-Example#8]
So I want to try canvas streaming to HLS.   Can this code be tweaked to do that?

Thanks,

Ray

**Comment by randallb** [comment]
hi Ray!

Do you mean you'd like this to send HLS from the backend ffmpeg to some other place? Or from the frontend instead of using websockets?

**Comment by randallb** [comment]
I haven't heard a response so I'll be closing this.
